CREATE TABLE NOTA
(
	RA NUMERIC(10)NOT NULL PRIMARY KEY,
	NOTA_PROVA1 NUMERIC (3,2)NOT NULL,
	NOTA_PROVA2 NUMERIC (3,2)NOT NULL,
	NOME VARCHAR(15)NOT NULL,
);


CREATE TABLE BOLETIM
(
	MEDIA NUMERIC(3,2)NOT NULL,

	
);


INSERT INTO NOTA VALUES(123456789,6.50,8.1,'Vitor');

select * from NOTA

CREATE TRIGGER MEDIA
ON NOTA
FOR INSERT
AS
BEGIN
	DECLARE @NOTA1 NUMERIC(3,2)
	DECLARE @NOTA2 NUMERIC(3,2)
	DECLARE @MEDIA NUMERIC(3,2)

	SELECT @NOTA1 = NOTA_PROVA1, @NOTA2 = NOTA_PROVA2 FROM INSERTED
	UPDATE BOLETIM SET @MEDIA = (@NOTA1+@NOTA2)/2			
	INSERT INTO BOLETIM (MEDIA) values (@MEDIA)

END

select * from BOLETIM;

select * from NOTA;

insert into NOTA values(1232131,6,9,'MARCO');


SELECT * FROM BOLETIM;

